CataniaUnited/catania-united-server

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- src/main/java/com/example/cataniaunited/service/Lobby.java
- src/main/java/com/example/cataniaunited/service/LobbyService.java
- src/main/java/com/example/cataniaunited/service/LobbyServiceImpl.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/dto/MessageDTOTest.java
- src/test/java/com/example/cataniaunited/service/LobbyServiceImplTest.java
- src/test/java/com/example/cataniaunited/service/LobbyTest.java
> 12 creating lobby

- src/main/java/com/example/cataniaunited/service/LobbyService.java
- src/main/java/com/example/cataniaunited/service/LobbyServiceImpl.java
- src/test/java/com/example/cataniaunited/service/LobbyServiceImplTest.java
Die Lobby-Id wurde folgerdermaßen generiert:
-  Die Lobby-ID besteht aus 6 Zeichen, bestehend aus 3 lower-case Buchstaben und 3 Ziffen
- Entweder beginnt die ID mit den lower-case Buchstaben und enden dann mit den Ziffern oder umgekehrt 
(z.B. "abc123" oder "456xyz")
> 18 - Receive Lobby Code

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerService.java
- src/main/java/com/example/cataniaunited/service/Lobby.java
- src/main/resources/META-INF/resources/index.html
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
i added all the necessary changes but better take a good look at it
> 16 view other players in lobby

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/service/Lobby.java
- src/main/resources/META-INF/resources/index.html
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
> 15 enter username in lobby

- src/main/java/com/example/cataniaunited/Publisher.java
- src/main/java/com/example/cataniaunited/Subscriber.java
Added interfaces to enable progress on other features
> #43-Add_general_Observer_pattern_interfaces:

- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/StandardTileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/Tile.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListDirector.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileType.java
- src/test/java/com/example/cataniaunited/game/board/tile_list_builder/StandardTileListBuilderTest.java
- src/test/java/com/example/cataniaunited/game/board/tile_list_builder/TileListDirectorTest.java
- src/test/java/com/example/cataniaunited/game/board/tile_list_builder/TileTest.java
added logic and tests for the value generation
> #3-Random_numbers_on_each_field:

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- src/main/java/com/example/cataniaunited/exception/GameException.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/main/java/com/example/cataniaunited/game/board/GraphBuilder.java
- src/main/java/com/example/cataniaunited/game/board/Road.java
- src/main/java/com/example/cataniaunited/game/board/SettlementPosition.java
- src/main/java/com/example/cataniaunited/game/buildings/Building.java
- src/main/java/com/example/cataniaunited/game/buildings/Settlement.java
- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/util/Util.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
- src/test/java/com/example/cataniaunited/game/board/GameBoardTest.java
- src/test/java/com/example/cataniaunited/game/board/RoadTest.java
- src/test/java/com/example/cataniaunited/game/board/SettlementPositionTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyServiceImplTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyTest.java
- Implemented GameService which should handle all ingame actions
- Added custom GameException to handle errors
- Implemented possibility to create gameboard for lobby
- Implemented possibility to place settlements and roads on the gameboard
- Improved readability and structure of GameWebSocket class
- Added tests for settlements and road placement
- Added tests for gameboard creation
- Added and improved tests for GameWebSocket
(sorry for very large commit but everything was so tangled up)
> #29 - Placing of settlement and road by first player:

- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerColor.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyServiceImplTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyTest.java
- src/test/java/com/example/cataniaunited/player/PlayerColorTest.java
1. 12 different player colors implemented: 
- RED("#BD2828")
- LIGHT_RED("FF9999")
- PURPLE("#B62FB2")
- LAVENDER("CCCCFF")
- BLUE("#0080B3")
- LIGHT_BLUE("B1DAE7")
- GREEN("#008000")
- LIGHT_GREEN("A7F1A7")
- ORANGE("#CF6D17")
- LIGHT_ORANGE("FFCC99")
- YELLOW("#DB9224")
- GREY("#999999")
2. Assigned a unique random color to each player when joining a lobby
3. Implemented removing a player from a lobby
4. Added color back to available colors when removing a player from a lobby
5. Reset player colors when clearing lobbies
> #19 - Selection of unique player color

- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
> #60 - fix sonarcloud problems because of unsafe use of arraylist in websocket test

- .github/workflows/build.yml
- build.gradle.kts
> #32 - Deployment on the uni server

- src/main/java/com/example/cataniaunited/exception/IntersectionOccupiedException.java
- src/main/java/com/example/cataniaunited/exception/NoAdjacentRoadException.java
- src/main/java/com/example/cataniaunited/exception/SpacingRuleViolationException.java
- src/main/java/com/example/cataniaunited/game/board/SettlementPosition.java
- src/test/java/com/example/cataniaunited/game/board/SettlementPositionTest.java
- Improved error messages when placing settlements and roads
> #8 - Placing-the-second-village-and-road-in-reverse-order:

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyServiceImplTest.java
- Added return value of hexcode of color for host when creating a lobby
- Added return value of hexCode of color for player when joining a lobby
- Updated tests in GameWebSocketTest
> #19-selection_of_unique_player_color:

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
- added live victory point updates to show player VPs live on gameScreen
- added leaderboard from all players and sorted it by victoryPoints to use it in the GameWonScreen in frontend
Closes #30
> #30-Checking_of_possible_win:

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- added temporary changes for app to work
> #12 - Host and join game

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/board/GameBoardTest.java
- fixed bug where resources would be removed from player even when building fails
> #5 - Building roads, settlements and cities:

- src/main/java/com/example/cataniaunited/Publisher.java
- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/game/Buildable.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/main/java/com/example/cataniaunited/game/board/GraphBuilder.java
- src/main/java/com/example/cataniaunited/game/board/Placable.java
- src/main/java/com/example/cataniaunited/game/board/Road.java
- src/main/java/com/example/cataniaunited/game/board/SettlementPosition.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/StandardTileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/Tile.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListDirector.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileType.java
- src/main/java/com/example/cataniaunited/game/buildings/Building.java
- src/main/java/com/example/cataniaunited/game/buildings/City.java
- src/main/java/com/example/cataniaunited/game/buildings/Settlement.java
- src/main/java/com/example/cataniaunited/game/dice/Dice.java
- src/main/java/com/example/cataniaunited/game/dice/DiceRoller.java
- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerColor.java
- src/main/java/com/example/cataniaunited/player/PlayerService.java
- src/main/java/com/example/cataniaunited/util/Util.java
Added Javadoc to all backend classes to simplify understanding of the codebase. Didn't touch any logic but marked a few potential issues found when looking thru the codebase.
> Add javadoc to make review easier

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyTest.java
fixed the issue where the second player joining the lobby was not displayed until placing a road
> 30 checking for win 3

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/resources/application.properties
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyServiceImplTest.java
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
Replace broadcast by lobby-only messaging
> 80 spielerkommunikation

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
Added missing null check when sending player resources
> 80 spielerkommunikation - Bug fixes

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
Replaced broadcast in GameService.broadcastWin() method with lobby-only messaging
> 80 spielerkommunikation fixes

- src/main/java/com/example/cataniaunited/api/GameWebSocket.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/main/java/com/example/cataniaunited/game/board/GraphBuilder.java
- src/main/java/com/example/cataniaunited/game/board/Road.java
- src/main/java/com/example/cataniaunited/game/board/SettlementPosition.java
- src/main/java/com/example/cataniaunited/game/board/ports/Port.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/StandardTileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/Tile.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListBuilder.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileListDirector.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileType.java
- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerService.java
- src/main/java/com/example/cataniaunited/util/Util.java
- src/test/java/com/example/cataniaunited/game/ResourceDistributionIntegrationTest.java
- src/test/java/com/example/cataniaunited/game/buildings/BuildingTest.java
- src/test/java/com/example/cataniaunited/player/PlayerColorTest.java
Please check the fixmes and implement reasonable fixes, considering you shouldn't refactor the whole architecture anymore
> Add fixmes from code review

- build.gradle.kts
- src/main/java/com/example/cataniaunited/api/GameMessageHandler.java
- src/main/java/com/example/cataniaunited/dto/MessageDTO.java
- src/main/java/com/example/cataniaunited/dto/MessageType.java
- src/main/java/com/example/cataniaunited/dto/PlayerInfo.java
- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/mapper/PlayerMapper.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerService.java
- src/test/java/com/example/cataniaunited/api/GameMessageHandlerTest.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyServiceImplTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyTest.java
- src/test/java/com/example/cataniaunited/mapper/PlayerMapperTest.java
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
- Implemented missing functionality for Lobby Screen
- Added PlayerInfo record as DTO, which contains all necessary information for the app
- Changed players List in MessageDto to map of playerId and PlayerInfo
- The PlayerInfo Map is now returned with every call, so that the app can utilize the information and update the frontend accordingly
- Removed manual building of JSON for players in the process
- Added MapStruct dependency
- Implemented PlayerMapper which maps a Player and Lobby Object to a PlayerInfo record
> 23 lobby screen

- src/main/java/com/example/cataniaunited/api/GameMessageHandler.java
- src/main/java/com/example/cataniaunited/dto/PlayerInfo.java
- src/main/java/com/example/cataniaunited/exception/ui/MissingRequiredStructuresException.java
- src/main/java/com/example/cataniaunited/exception/ui/SetupLimitExceededException.java
- src/main/java/com/example/cataniaunited/game/BuildRequest.java
- src/main/java/com/example/cataniaunited/game/GameService.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/main/java/com/example/cataniaunited/game/board/tile_list_builder/TileType.java
- src/main/java/com/example/cataniaunited/lobby/Lobby.java
- src/main/java/com/example/cataniaunited/lobby/LobbyService.java
- src/main/java/com/example/cataniaunited/lobby/LobbyServiceImpl.java
- src/main/java/com/example/cataniaunited/mapper/PlayerMapper.java
- src/main/java/com/example/cataniaunited/player/Player.java
- src/main/java/com/example/cataniaunited/player/PlayerService.java
- src/main/resources/application.properties
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
- src/test/java/com/example/cataniaunited/game/ResourceDistributionIntegrationTest.java
- src/test/java/com/example/cataniaunited/game/board/GameBoardTest.java
- src/test/java/com/example/cataniaunited/lobby/LobbyTest.java
- src/test/java/com/example/cataniaunited/mapper/PlayerMapperTest.java
- src/test/java/com/example/cataniaunited/player/PlayerServiceTest.java
- src/test/java/com/example/cataniaunited/player/PlayerTest.java
- Implemented functionality, that players are must place exactly one road and one settlement in each of the two setup rounds
- Player resources are now initialized on game start and not when the app is opened. That means that for each new game the resources are reset again.
> 24 receive starting resources from second settlement

- src/main/java/com/example/cataniaunited/game/BuildRequest.java
- src/main/java/com/example/cataniaunited/game/board/GameBoard.java
- src/main/java/com/example/cataniaunited/game/board/Road.java
- src/test/java/com/example/cataniaunited/game/board/GameBoardTest.java
Outside of setup rounds, roads can now only be placed adjacent to already owned roads
> #106 - Fix road placement

- src/main/java/com/example/cataniaunited/game/GameService.java
- src/test/java/com/example/cataniaunited/api/GameWebSocketTest.java
- src/test/java/com/example/cataniaunited/game/GameServiceTest.java
- fixed bug where upgrade of settlement was possible during setup rounds
> #24 - Receive starting resources from second settlement:
